// ============================================================
// SITEMAP + ROBOTS GENERATOR
//
// Runs before `vite build` (see package.json "prebuild").
// Produces public/sitemap.xml and public/robots.txt using the
// production domain from VITE_SITE_URL — so nothing is hardcoded
// and both files update automatically when the domain changes.
//
// Run manually:  node scripts/generate-sitemap.mjs
// ============================================================

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { indexableRoutes } from "../src/data/routes.js";

const FALLBACK_SITE_URL = "https://awad-educational-academy.vercel.app";

function resolveSiteUrl() {
  const raw = (process.env.VITE_SITE_URL || FALLBACK_SITE_URL).trim();
  return raw.replace(/\/+$/, "");
}

const SITE_URL = resolveSiteUrl();
const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = resolve(__dirname, "..", "public");
const lastmod = new Date().toISOString().split("T")[0];

function buildSitemap() {
  const urls = indexableRoutes
    .map((r) => {
      const loc = `${SITE_URL}${r.path === "/" ? "/" : r.path}`;
      return [
        "  <url>",
        `    <loc>${loc}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${r.changefreq}</changefreq>`,
        `    <priority>${r.priority.toFixed(1)}</priority>`,
        "  </url>",
      ].join("\n");
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function buildRobots() {
  return `# robots.txt — Awad Educational Academy
# Generated by scripts/generate-sitemap.mjs

User-agent: *
Allow: /

# Nothing sensitive to disallow yet. Add private/admin routes here
# if they are introduced in future, e.g.:
# Disallow: /admin
# Disallow: /draft

Sitemap: ${SITE_URL}/sitemap.xml
`;
}

async function main() {
  await writeFile(resolve(publicDir, "sitemap.xml"), buildSitemap(), "utf8");
  await writeFile(resolve(publicDir, "robots.txt"), buildRobots(), "utf8");
  console.log(`[seo] Generated sitemap.xml + robots.txt for ${SITE_URL}`);
}

main().catch((err) => {
  console.error("[seo] Failed to generate sitemap/robots:", err);
  process.exit(1);
});
